### ISSUE TITLE
the bot dont joins my voice channel

### ISSUE THREAD

**Issue by ShrimantaGarain** [0x0is1/helina-discord-radio#1]
its shows playing but dont join my vc HELP!!

**Comment by 0x0is1** [comment]
Hello. Sorry for inconvenience, can you please attach screenshot and explain the issue lil more? Thank you.

**Comment by 0x0is1** [comment]
Are you sure proper voice permissions are given to your bot?

**Comment by ShrimantaGarain** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/51848590/134665328-6e964367-68b6-4a01-be85-ccaaad8dcfe5.png)

am in VC and my bot is given an admin  role..... still bot cant join VC

**Comment by ShrimantaGarain** [comment]
OH, it's working now. thank you.

**Comment by 0x0is1** [comment]
We are adding radio station from all over the world soon. Stay tuned. Thank you

**Comment by ShrimantaGarain** [comment]
great work bro carry on!!
